#!/bin/bash
import os,platform
os.system('clear')
os.system('git pull')
bit = platform.architecture()[0]
if bit=='32bit':
    print('YOUR DEVICE 32 BIT')
    print('32 BIT NOT AVAIABLE NOW')
elif bit=='64bit':
    print('YOUR DEVICE 64 BIT ')
    python -c "import Dump; Dump.SAQI_APPROVAL()"
